#!/bin/sh

# Print header
cat << 'EOF' > comments_generated.h
/* Autogenerated file */
#include "../common/logic-common.h"

typedef struct comment_t { word_t addr; char *comment; } comment_t;

comment_t comments[]= {
EOF

# Include comments from Decode.txt for MAPROM entry points for ISA opcodes
cat Comments/Decode.txt | awk '
	/0x[0-9a-f][0-9a-f] / {
		sub(/0x/,"0x1",$1);
		cmt=substr($0,8);
		sub(/^[[:space:]]*/,"",cmt);
		print "\t{"$1 ", \"MAPROM Entry Point: " cmt "\"},";
	};
' >> comments_generated.h

# Include additional comments from Comments.txt
cat Comments/Comments.txt | awk '
	BEGIN {FS="\t";};
	/0x[0-9a-f][0-9a-f][0-9a-f]/ {
		print "\t{"$1 ", \"" $2 "\"},";
	};
' >> comments_generated.h

# Include sjsoftware's hand-disassembly comments from bootstrap.txt
cat Comments/sjsoftware/bootstrap.txt | awk '
	/\([0-9a-f][0-9a-f][0-9a-f]\)[[:space:]]+;/ {
		addr=substr($0,132,3);
		cmt=substr($0,139);
		print "\t{0x" addr ", \"sjsoftware: " cmt "\"},";
	};
' >> comments_generated.h

# Print the last entry and close the array
printf "\t{0,0}\n};\n" >> comments_generated.h
